
create table `bet` (
    `id` bigint not null auto_increment comment '主键id',
    `member_account` varchar(64) not null comment '玩家账号',
    `currency` varchar(16) not null comment '币别',
    `game_id` varchar(32) not null comment '游戏编号',
    `ts` bigint not null comment '发送请求当下事件',
    `record_id` varchar(255) not null comment '游戏记录编号(唯一)',
    `bank_id` varchar(255) not null comment '交易单号(唯一)',
    `game_type` int(6) not null comment '游戏类型',
    `is_buy_feature` tinyint(1) not null default 0 comment '是否购买免费游戏',
    `bet` double(10,4) not null default 0.00 comment '押注金额',
    `win` double(10,4) not null default 0.00 comment '游戏赢分',
    `jp_bet` double(10,4) not null default 0.00 comment '彩金押注金额',
    `jp_prize` double(10,4) not null default 0.00 comment '彩金赢分',
    `net_win` double(10,4) not null default 0.00 comment '总输赢',
    `require_amt` double(10,4) null default 0.00 comment '实际押注金额(仅推币机与捕鱼机)',
    `game_date` datetime not null comment '游戏时间',
    `create_date` datetime not null comment '交易建立事件',
    `has_back_water` tinyint(1) not null default 0 comment '是否返水,0未返水,1已返水',
    `user_id` bigint not null comment '用户id',
    `has_settled` tinyint(1) not null default 0 comment '是否结算 0未结算,1已结算',
    `has_cancel` tinyint(1) not null default 0 comment '是否取消,0未取消,1已取消',
    `create_time` datetime not null comment '创建时间',
    `update_time` datetime null comment '更新时间',
    `game_name` varchar(64) null comment '游戏名称',
    primary key (`id`),
    UNIQUE `uq_bank_id` (`bank_id`),
    UNIQUE `uq_record_id` (record_id),
    key `idx_user_id` (`user_id`)
) comment = '下注记录表';